version: '3.7'

services:
  web:
    build: .
    container_name: rdm-web
    ports:
      - "8080:80"
    volumes:
      - ./rdm:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: rdm-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rdm
      MYSQL_USER: rdmuser
      MYSQL_PASSWORD: rdm123
    ports:
      - "3306:3306"
